# -*- coding: utf-8 -*-
"""assignment5.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11DxhIfdLsBVLkcsgApdbLFp2mXLs3i9a
"""

def most_frequent(input_string):
    letter_frequency = {}
    for char in input_string:
        if char in letter_frequency:
            letter_frequency[char] += 1
        else:
            letter_frequency[char] = 1
    return letter_frequency
def main():
    input_string = input("Enter a string: ")
    frequency_result = most_frequent(input_string)
    print("\nLetter Frequencies:")
    for char, freq in frequency_result.items():
        print(f"'{char}': {freq}")
if __name__ == "__main__":
    main()