# -*- coding: utf-8 -*-
"""task2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14VGqnHNWJLGndN1L87qqIkL0evZBUzDM
"""

x=input("the name of the file is:")
pos=x.index(".")
print(pos)
myDict={
    ".py"=="python",
    ".doc"=="word",
    ".java"=="java"
}
if x[pos:]==".py":
    print("python")
elif x[pos:]==".doc":
    print("word")
elif x[pos:]==".java":
    print("java")