# -*- coding: utf-8 -*-
"""assignment6.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lAJFdVl7T1c3pdeSTzkmeTEJA-sCCBRt
"""

import csv

def write_into_csv(info_list):
    with open('student_info.csv','a',newline='') as csv_file:
        writer=csv.writer(csv_file)
        if csv_file.tell()==0:
          writer.writerow(["name","age","contact_no.","email-id"])
        writer.writerow(info_list)
if __name__=='__main__':
  c=True
  while(c):
      student_info=input("enter student information in the following format (name age contact_no. email_id):")
      print("entered information:"+student_info)
      student_info_list=student_info.split(' ')
      print("entered split up information is:"+str(student_info_list))
      write_into_csv(student_info_list)
      another_input=input("enter yes/no to if you want to enter information of another student")
      if another_input=="yes":
          c=True
        elif another_input=="no":
            c=False