# -*- coding: utf-8 -*-
"""assignment4.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oGLG1-ePMifX2qM5JVIa9VKSSS3cPN2k
"""

a=0
b=1
c=0
n=int(input("enter how many numbers you want to print in the series:"))
print(a)
print(b)
for i in range(3,n):
    c=a+b
    a=b
    b=c
    print(c )