# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sytywl0W2A9uJaYAE27jg3fh8xdcRHYO
"""

x=float(input("radius of circle is:"))
print(3.14*x*x)